### ISSUE TITLE
The placeholder isn't work in 1.16.4

### ISSUE THREAD

**Issue by Tatado2020** [matahombres/Advancements#1]
Help! I want to check a player if have acquire diamonds advancement, then i use the papi "%advancements_mine_diamond%", then indication "NO_EXIST_ADVANCEMENT", and I tried to use %Advancements_remainingAmount_%, then indication "NO_WORKING"

**Comment by matahombres** [comment]
there really is no such advancement
https://minecraft.gamepedia.com/Advancement

The only thing you lack is the "group" or tab to which the advancement belongs.
Example:
story/mine_diamond
nether/find_fortress
....

If you use `%Advancements_playerListFormat_<player>%` can show list of advancement
