### ISSUE TITLE
[Suggestion] add placeholders that add deluxechat, leaderboard etc. support

### ISSUE THREAD

**Issue by larssieboy18** [matahombres/Advancements#2]
Hi there, I was trying to add the placeholders to deluxechat, but it seems like the advancements placeholders don't support {player_name}, which makes it impossible to have a general placeholder in Deluxechat, e.g. %Advancements_completedAmount_{player_name}%. I would really like to see the possibility of %Advancements_completedAmount_{player_name}% and %Advancements_remainingAmount_{player_name}%, please let me know if it is possible!

**Comment by matahombres** [comment]
It should work, since that's something the placeholderAPI handles.
I will check it anyway
